### ISSUE TITLE
Procedure to setup ERPNext to a lower version - FAILS

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#83]
I have been attempting to get this to work now for about 4 hours.

The first time I tried it was on a GCP test server because I can spin them up very fast., I managed to get through the entire set of instructions, but was unable to get the setup process to run because it failed to allow a login of the Administrator.

After that, I loaded up another fresh GCP server and tried again (actually I tried 3 more times) and every time It failed near the beginning of the process with the following trace:

```
TASK [locale : Check current locale] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "localectl", "delta": "0:00:00.049899", "end": "2018-09-04 
16:34:43.008103", "msg": "non-zero return code", "rc": 1, "start": "2018-09-04 16:34:42.958204", "stderr": "Could n
ot get properties: Connection timed out", "stderr_lines": ["Could not get properties: Connection timed out"], "stdo
ut": "", "stdout_lines": []}
        to retry, use: --limit @/tmp/.bench/playbooks/site.retry
PLAY RECAP ********************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1   
Traceback (most recent call last):
  File "install.py", line 420, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.jso
n', '--become', '--become-user=erp_jmi']' returned non-zero exit status 2

```
--------------------------------------------------------------------------------------

Thinking there might be something wrong with using the GCP servers, I tried it on the Interserver test host 209.159.154.155 and it also failed early in the install.py script with the following trace:

```
Successfully installed asn1crypto-0.24.0 certifi-2018.8.24 cffi-1.11.5 chardet-3     .0.4 cryptography-2.3.1 idna-2.7 pycparser-2.18 requests-2.19.1 setuptools-40.2.     0 urllib3-1.23
sudo: unable to resolve host ubuntu16.is.cc
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line      42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cmdoptions.py", lin     e 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index.py", line 14,      in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py"     , line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyope     nssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <modul     e>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "install.py", line 420, in <module>
    install_bench(args)
  File "install.py", line 58, in install_bench
    'pip': "sudo pip install --upgrade urllib3 requests cryptography ansible"
  File "install.py", line 234, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo pip install --upgrade urllib3 reque     sts cryptography ansible' returned non-zero exit status 1
```

I have re-installed the OS on the Interserver 2 additional times and it now always fails with the above trace.

Here are my concerns:

- It appears you are using the install.py right from the main ERPNext install location. Is this true?

- It also appears, that during my testing, someone has altered either the install.py or the playbook. I have encountered something like this before and found that someone had indeed altered the scripts.

- Even when I was able to get it to install the first time on GCP test server, it still had 2 benches and there did not appear to be a way to tell the login screen which site I was attempting to log into. This may be why it failed at the Administrator login?

- It appears that your instructions are attempting to use the last version of erpnext to do an install, and then to select the special masters AFTER the install, then setup a new bench with the new masters to get the type of installation I want. This does not seem like a sound approach because I end up with 2 benches in one install and no way to differentiate at the initial login.

- I also know that there are several switches available to use with the install.py script like:
" --without-site"
" --bench-branch"
" --repo-url"
" --frappe-repo-url"
" --frappe-branch"
" --erpnext-repo-url"
" --erpnext-branch"
" --without-erpnext"
" --without-bench-setup"
Is there any way to use some combination of these switches to make the install use the correct branches at the very beginning, or even to only install partial system before assigning the new branches to complete the install?

- If the potential for changes to the main erpnext sources (including the install.py and playbook) exists that could cause my installs to fail, then maybe we need our own fork of the system so that nothing ever changes to cause problems. I think I would actually prefer this idea to make everything frozen permanently. 

Please let me know where we go from here. The current instruction plans do not work.

I am currently re-installing the Ubuntu operating system again on the 209.159.154.155 server and will send you an email when it is ready and the login credentials so you can try this yourself to see my errors. You also have access to the CGP account. You could also spin up a fresh server there to try if you wanted.

Please advise the next step.

BKM

**Comment by bkm888** [comment]
It is now about 6 hours after my first attempt to get the instructions to work and I have gone back to GCP to spin up a quick Ubuntu server to try it again. O wanted to see if the install.py script had been fixed since my last effort.

Well, this time the installation completed, but the end result is still the same.  

At instruction #8 - I open a browser and type in the ip address of the new server and I am presented with a ERPNExt login screen. I fill in the Administrator login credentials and hit the enter key. At first I get what appears to be a "Success" message above the login window:

![image](https://user-images.githubusercontent.com/30693364/45064624-df191480-b082-11e8-9727-92902889f6f0.png)


Then in about 2 seconds I get the following error message:

![image](https://user-images.githubusercontent.com/30693364/45064491-20f58b00-b082-11e8-96fd-03c7d4dc4844.png)

This is the same message I got the very first time I tried the instructions. Every time after that the install script failed. My guess is that someone went back in and fixed the install script in the past 6 hours.

I still do not have a working set of instructions.
I also would prefer to have an installed system with only one site and not 2 so that there is no question about which site is being used.

Please advise.

BKM

**Comment by mckaygerhard** [comment]
hi @bkm888 seems you are search for a erp or pos related system right?

**Comment by gaurav-naik** [comment]
Siddhi and I are trying to install ERPNext on mnt-frozen-install-test-2 using [the Hitchhiker's guide](https://github.com/frappe/frappe/wiki/The-Hitchhiker's-Guide-to-Installing-Frapp%C3%A9-on-Linux-OS) instead of the easy install script.

While easy install worked on the test production server (with some manual intervention), it threw new errors on the mnt-frozen servers, which is why we decided to use a different approach.

We will keep you up-to-date regarding the progress here.

**Comment by bkm888** [comment]
@gaurav-naik @Siddhisawant8 

I appreciate the effort, but also be aware that the easy install script with your modification did NOT produce a usable installation. Even that effort has somehow damaged the usability of MariaDB to the point that it constantly timed out. This was detailed in an email to the team several days ago.

Please make sure any new procedure does not take any of the processes concerning the database form the previous effort.

BKM

**Comment by bkm888** [comment]
@gaurav-naik @Siddhisawant8 
I wanted to have a look at what you may have been doing with the 209.159.154.155 server to see if you had been able to correct the mariadb time out issue. What ever has been going on there, the server is no longer functional.

Have you made changes to it?
Are you able to reach it by ssh client?
Should I just wipe it and re-install the OS?

Let me know.
BKM

**Comment by bkm888** [comment]
I have reset the server to get it working again with ssh client. 
Let me know what is happening there.

BKM

**Comment by gaurav-naik** [comment]
Kindly reinstall the OS. I will attempt to reinstall using the Hitchhikers
guide for installing Frappe in the next few hours.

**Comment by bkm888** [comment]
@gaurav-naik @Siddhisawant8 

Ok, the OS has been re-installed and and completely updated.
All login credentials are that same.

Let me know if you need anything else.

BKM

**Comment by gaurav-naik** [comment]
We have made headway in installing ERPNext using the Hitchhiker's guide on mnt-frozen-install-2. There is a sticky bench-level issue which prevents us from creating a new site on the server. 
Once resolved, the plan is to have the same steps repeated on mnt-frozen-install-1 and if successful, share the updated instructions so that you may try them out on the production server.

I will have an update regarding this issue within the next 4 hours.

**Comment by bkm888** [comment]
@gaurav-naik @Siddhisawant8 
Is it possible that there have been changes made to the frappe core that are interfering with the site install?
I only ask because I noticed in the Hitch hikers Guide to frappe there is the command:
```
$ git clone https://github.com/frappe/bench
$ sudo pip install ./bench
```
And it seems that this would be pulling in the most recent version of bench and maybe not the version that was active when the JMI ERPNext version was first installed back in Feb.

At that time the bench version was 4.1.0

Just an observation... not meant to interfere with your work.

BKM

**Comment by bkm888** [comment]
Evidently there is someone on the ERPNExt forums attempting to something similar. There is a lot of good information in [THIS THREAD](https://discuss.erpnext.com/t/how-to-install-a-specific-version-of-erpnext/41001) on the forum which might be helpful to your efforts.

BKM

**Comment by gaurav-naik** [comment]
@bkm888 
I was able to setup bench using the manual install (not Hitchhiker's guide) with some back-and-forth. I would like to retry the steps before sharing them with you. Kindly reset all three servers one more time so that I may try the steps out again.

I will update the status here once I have stable setup. It should not take long after the reset.

**Comment by bkm888** [comment]
Gaurav,

The 2 GCP servers are already reset and ready for you. The new IP addresses are:
35.231.120.84     mnt-frozen-install-test-1
35.196.5 91         mnt-frozen-install-test-2

The Interserver (209.159.154.155) server is currently having the OS re-installed and should be ready in about an hour. The login credentials for all of the above will remain the same.

BKM

**Comment by bkm888** [comment]
@gaurav-naik 

Ok, now all three servers are ready for your work.

BKM

**Comment by gaurav-naik** [comment]
Thank you Bryan. I will notify you once I'm able to follow my steps
successfully.
